# Generated by Django 5.2.1 on 2025-05-30 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('tipo_comida', models.CharField(max_length=100)),
                ('capacidad_personas', models.IntegerField(blank=True, null=True)),
                ('incluye_bebidas', models.BooleanField(default=False)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decoradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('estilo_especialidad', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios_incluidos', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('url_portafolio', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_grupo', models.CharField(max_length=100)),
                ('Años_trayec', models.IntegerField(blank=True, null=True)),
                ('Numero_music', models.IntegerField(blank=True, null=True)),
                ('costos_paquetes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('Costo_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('URL', models.URLField(blank=True, max_length=255, null=True)),
                ('Genero', models.CharField(choices=[('Sonideros', 'Sonideros'), ('Rancheros', 'Rancheros'), ('Cumbias', 'Cumbias'), ('Mariachis', 'Mariachis'), ('Baladas', 'Baladas')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requiere_detalles', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mobiliario', models.CharField(choices=[('Sillas', 'Sillas'), ('Mesas', 'Mesas'), ('Carpas', 'Carpas')], max_length=100)),
                ('cantidad_disponible', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalonesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_salon', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('incluye_estacionamiento', models.BooleanField(default=False)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('precio_renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Direccion_envio', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='activo', max_length=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cuotas_credito', models.IntegerField(blank=True, null=True)),
                ('intervalo_cuotas', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Nombre_Cat', models.CharField(choices=[('Grupos Musicales', 'Grupos Musicales'), ('Banquetes', 'Banquetes'), ('Salones de Eventos', 'Salones de Eventos'), ('Mobiliario', 'Mobiliario'), ('Decoradores', 'Decoradores')], max_length=100, primary_key=True, serialize=False, verbose_name='Nombre de Categoría')),
                ('id_banquete', models.ForeignKey(blank=True, db_column='id_banquete', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.banquetes')),
                ('id_decorador', models.ForeignKey(blank=True, db_column='id_decorador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.decoradores')),
                ('id_grupo', models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.grupos')),
                ('id_mobiliario', models.ForeignKey(blank=True, db_column='id_mobiliario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mobiliario')),
                ('id_salon', models.ForeignKey(blank=True, db_column='id_salon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.saloneseventos')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('direccion_envio', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.metodopago')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('xml_factura', models.TextField(blank=True, null=True)),
                ('pdf_factura', models.BinaryField(blank=True, null=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('Nombre_Cat', models.ForeignKey(db_column='Nombre_Cat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
        ),
    ]
